src/accounts/urls.py
from django.urls import path
from accounts.views import (
    UpdateStudentView,
    DeleteStudentView,
    StudentListView,
    FileDownloadView,
    GroupListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
    TeachersListView,
    CreateTeacherView,
    UpdateTeacherView,
    DeleteTeacherView,
    ShowGroupsView,
)

app_name = "accounts"

urlpatterns = [
    path("", StudentListView.as_view(), name="get_students"),
    path("update/<str:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<str:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("download/<uuid:pk>/", FileDownloadView.as_view(), name="download_pdf_file"),
    path("get-groups/", GroupListView.as_view(), name="get_groups"),
    path("create-group/", CreateGroupView.as_view(), name="create_group"),
    path("update-group/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete-group/<int:pk>", DeleteGroupView.as_view(), name="delete_group"),
    path("get-teachers", TeachersListView.as_view(), name="get_teachers"),
    path("create-teacher/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update-teacher/<str:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete-teacher/<str:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
    path("show-groups/<str:pk>/", ShowGroupsView.as_view(), name="show_groups"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
    UserRegistrationView,
    UserLoginView,
    ActivateUserView,
    CustomUserProfileUpdateView,
    UserLogOutView,
    CustomUserProfileView,
    PrivacyPolicyView,
    CustomUserUpdateView,
    IndexView,
)
from accounts.views import NotFoundView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("registration/", UserRegistrationView.as_view(), name="user_registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate"),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogOutView.as_view(), name="logout"),
    path("profile/<str:username>/", CustomUserProfileView.as_view(), name="profile"),
    path("user_settings/<uuid:pk>/", CustomUserUpdateView.as_view(), name="edit_customuser"),
    path("edit_profile/<uuid:pk>/", CustomUserProfileUpdateView.as_view(), name="edit_profile"),
    path("privacy_policy/", PrivacyPolicyView.as_view(), name="privacy"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = NotFoundView.as_view()

src/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError

from django.forms import ModelForm, EmailField, CharField, PasswordInput
from phonenumber_field.formfields import PhoneNumberField


from accounts.models import CustomUser, Profile, Group
from django.utils.translation import gettext_lazy as _


class CustomUserCreationForm(UserCreationForm):
    phone_number = PhoneNumberField()
    email = EmailField(max_length=200, help_text="Please use your working email")

    class Meta:
        model = CustomUser
        fields = (
            "phone_number",
            "email",
            "username",
            "is_student",
            "is_teacher",
            "is_mentor",
            "password1",
            "password2",
        )

    def clean(self):
        cleaned_data = super().clean()
        # extend parent method,  not overwrite

        student = self.cleaned_data.get("is_student")
        teacher = self.cleaned_data.get("is_teacher")
        mentor = self.cleaned_data.get("is_mentor")

        if student:
            if teacher or mentor:
                raise ValidationError("Student cannot be a teacher or mentor")
        return cleaned_data

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get("phone_number")
        phone_number_qs = CustomUser.objects.filter(phone_number=phone_number)
        if phone_number_qs.exists():
            raise ValidationError("Phone number already exists")
        return phone_number

    def clean_username(self):
        username = self.cleaned_data.get("username")
        username_qs = CustomUser.objects.filter(username=username)
        if username_qs.exists():
            raise ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data.get("email")
        email_qs = CustomUser.objects.filter(email=email)
        if email_qs.exists():
            raise ValidationError("This email has been already in use")
        return email


class CustomUserChangeForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            "email",
            "username",
            "phone_number",
            "is_student",
            "is_teacher",
            "is_mentor",
        )


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = (
            "birthdate",
            "photo",
            "first_name",
            "last_name",
            "job_title",
        )


class CustomLoginForm(AuthenticationForm):
    password = CharField(
        label=_("Password"),
        strip=False,
        widget=PasswordInput(attrs={"autocomplete": "current-password"}),
    )


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ("department", "classroom")


# class TeacherForm(ModelForm):
#     class Meta:
#         model = Teacher
#         fields = ("first_name", "last_name", "email", "birthday", "experience")
#
#     def clean_email(self):
#         email = self.cleaned_data["email"]
#
#         if "@yandex" in email.lower():
#             raise ValidationError("Yandex domain is forbidden")
#
#         return email
#
#     @staticmethod
#     def normalize_text(text):
#         return text.strip().capitalize()
#
#     def clean_first_name(self):
#         return self.normalize_text(self.cleaned_data["first_name"])
#
#     def clean_last_name(self):
#         return self.normalize_text(self.cleaned_data["last_name"])
#
#     def clean(self):
#         cleaned_data = super().clean()
#         # extend parent method,  not overwrite
#
#         first_name = cleaned_data["first_name"]
#         last_name = cleaned_data["last_name"]
#
#         if first_name == last_name:
#             raise ValidationError("First name and last name can't be equal")
#
#         return cleaned_data

src/accounts/views.py
import os

from django.contrib.auth import login
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import Permission
from django.contrib.auth.views import LoginView, LogoutView, redirect_to_login
from django.forms.utils import ErrorList
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from django.views import View

from django.views.generic import UpdateView, DeleteView, CreateView, ListView, RedirectView, DetailView, TemplateView


from accounts.forms import CustomUserCreationForm, CustomUserChangeForm, CustomLoginForm, ProfileForm
from accounts.models import CustomUser, Profile, Group
from accounts.services.emails import send_registration_email
from accounts.utils.token_generator import TokenGenerator

from accounts.forms import GroupForm


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect_to_login(self.request.get_full_path(), self.get_login_url(), self.get_redirect_field_name())
        if not self.has_permission():
            return redirect("login")
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)


class IndexView(TemplateView):
    template_name = "index.html"
    http_method_names = ["get"]

    def get(self, request, *args, **kwargs):
        print("inside request")
        print(request)
        print(kwargs)
        print(args)
        print("current time is: ", self.request.current_time)
        return super().get(request, *args, **kwargs)


class StudentListView(ListView):
    model = CustomUser
    context_object_name = "students"
    template_name = "students_list.html"
    queryset = CustomUser.objects.filter(is_student=True)


class UpdateStudentView(UserAccessMixin, UpdateView):
    permission_required = "accounts.delete_student"
    login_url = "login"
    redirect_field_name = "next"

    model = CustomUser
    template_name = "edit_student.html"
    success_url = reverse_lazy("accounts:get_students")
    form_class = CustomUserChangeForm


class DeleteStudentView(UserAccessMixin, DeleteView):
    permission_required = "accounts.delete_student"
    login_url = "login"
    redirect_field_name = "next"

    model = CustomUser
    success_url = reverse_lazy("accounts:get_students")
    template_name = "delete_confirm_student.html"


class FileDownloadView(UserAccessMixin, View):
    permission_required = "accounts.change_student"
    login_url = "login"
    redirect_field_name = "next"

    model = CustomUser
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    folder_path = BASE_DIR + "/media/images/student/cv/"
    filename = ""
    content_type_value = "application/pdf"

    def get(self, request, pk):
        student = get_object_or_404(CustomUser, pk=pk)
        filename = student.filename
        file_path = os.path.join(self.folder_path, filename)
        if os.path.exists(file_path):
            with open(file_path, "rb") as fh:
                response = HttpResponse(fh.read(), content_type=self.content_type_value)
                response["Content-Disposition"] = "attachment; filename=" + os.path.basename(file_path)
            return response
        else:
            raise Http404


class UserLoginView(LoginView):
    form_class = CustomLoginForm
    template_name = "registration/login.html"

    # def get_success_url(self):
    #     return reverse("profile", args=[self.request.user.username]) or self.get_default_redirect_url()

    def get_default_redirect_url(self):
        return reverse("index")


class UserLogOutView(LogoutView):
    next_page = reverse_lazy("login")


class UserRegistrationView(CreateView):
    template_name = "registration/registration.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("index")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        send_registration_email(request=self.request, user_instance=self.object)
        return super().form_valid(form)


class ActivateUserView(RedirectView):
    url = reverse_lazy("index")

    def get(self, request, uuid64, token, backend="django.contrib.auth.backends.ModelBackend", *args, **kwargs):
        try:
            pk = force_str(urlsafe_base64_decode(uuid64))
            current_user = CustomUser.objects.get(pk=pk)
        except (CustomUser.DoesNotExist, TypeError, ValueError):
            return HttpResponse("Wrong data")

        if current_user and TokenGenerator().check_token(current_user, token):
            perm1 = Permission.objects.get(codename="change_profile")
            perm2 = Permission.objects.get(codename="view_profile")
            current_user.is_active = True
            current_user.user_permissions.add(perm1, perm2)
            current_user.backend = "django.contrib.auth.backends.ModelBackend"
            current_user.save()

            login(request, current_user)
            return super().get(request, *args, **kwargs)

        return HttpResponse("Wrong data")


class CustomUserUpdateView(UserAccessMixin, UpdateView):
    permission_required = "accounts.change_customuser"
    model = CustomUser
    form_class = CustomUserChangeForm
    success_url = reverse_lazy("index")
    template_name = "update_customuser.html"


class CustomUserProfileView(UserAccessMixin, DetailView):
    model = Profile
    permission_required = "accounts.view_profile"
    template_name = "view_user_profile.html"

    def get_object(self):
        return get_object_or_404(Profile, user__username=self.kwargs["username"])


class CustomUserProfileUpdateView(UserAccessMixin, UpdateView):
    permission_required = "accounts.change_profile"
    login_url = "login"
    redirect_field_name = "next"
    model = Profile
    template_name = "edit_user_profile.html"
    success_url = reverse_lazy("index")
    form_class = ProfileForm

    def get_object(self):
        return get_object_or_404(Profile, user__id=self.kwargs["pk"])


class PrivacyPolicyView(TemplateView):
    template_name = "privacy_policy.html"


class TeachersListView(ListView):
    model = CustomUser
    context_object_name = "teachers"
    template_name = "teachers_list.html"
    queryset = CustomUser.objects.filter(is_teacher=True)


class CreateTeacherView(UserAccessMixin, CreateView):
    permission_required = "teachers.change_teacher"
    login_url = "student_login"
    redirect_field_name = "next"

    template_name = "teachers_create.html"
    model = CustomUser
    fields = "__all__"
    success_url = reverse_lazy("teachers:get_teachers")
    initial = {"first_name": "John", "last_name": "Doe"}

    def form_valid(self, form):
        self.object = form.save(commit=False)
        first_name = form.cleaned_data["first_name"]
        last_name = form.cleaned_data["last_name"]
        if first_name == last_name:
            form._errors["first_name"] = ErrorList(["First and last names can't be equal"])
            form._errors["last_name"] = ErrorList(["First and last names can't be equal"])
            return super().form_invalid(form)
        return super().form_valid(form)


class UpdateTeacherView(UserAccessMixin, UpdateView):
    permission_required = "teachers.change_teacher"
    login_url = "student_login"
    redirect_field_name = "next"

    model = CustomUser
    template_name = "edit_teacher.html"
    fields = "__all__"
    success_url = reverse_lazy("accounts:get_teachers")
    http_method_names = ["get", "post"]


class DeleteTeacherView(UserAccessMixin, DeleteView):
    permission_required = "accounts.delete_customuser"
    login_url = "student_login"
    redirect_field_name = "next"

    model = CustomUser
    success_url = reverse_lazy("accounts:get_teachers")
    template_name = "delete_confirm_teacher.html"


class ShowGroupsView(DetailView):
    model = CustomUser
    template_name = "show_groups.html"


class GroupListView(ListView):
    model = Group
    context_object_name = "groups"
    template_name = "groups_list.html"
    queryset = Group.objects.all()


class CreateGroupView(UserAccessMixin, CreateView):
    permission_required = "accounts.change_student"
    login_url = "accounts:get_groups"
    redirect_field_name = "next"

    template_name = "src/accounts/templates/create_group.html"
    model = Group
    form_class = GroupForm
    success_url = reverse_lazy("accounts:get_groups")


class UpdateGroupView(UserAccessMixin, UpdateView):
    permission_required = "accounts.change_student"
    login_url = "accounts:get_groups"
    redirect_field_name = "next"

    model = Group
    template_name = "edit_teacher.html"
    success_url = reverse_lazy("accounts:get_groups")
    form_class = GroupForm


class DeleteGroupView(UserAccessMixin, DeleteView):
    permission_required = "accounts.delete_group"
    model = Group
    success_url = reverse_lazy("accounts:get_groups")
    template_name = "delete_confirm_group.html"


class NotFoundView(TemplateView):
    template_name = "404.html"

src/accounts/templates/create_group.html
{% extends "src/templates/index.html" %}
{% load crispy_forms_tags %}
{% include static %}

{% block content %}
    <div>
        <form method="POST" class="create-form">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Create" class="btn btn-success">
                    Create
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/delete_confirm_group.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Delete" class="btn btn-warning">
                    Are you sure you want to delete {{ object.get_department_display }}?
                </button>
            </p>
            <a href="{% url 'accounts:get_groups' %}"
           class="btn btn-sm btn-success border-white ">Go back to groups</a>
        </form>
    </div>
{% endblock %}

src/accounts/templates/delete_confirm_student.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <h3>{{ object.first_name }} {{ object.last_name }}</h3>
                <h5>Age: {{ object.age }} year(s)</h5>
                <h5>{{ object.group }} </h5>
                <h5>Grade: {{ object.grade }} </h5>
                <button type="submit" value="Delete" class="btn btn-warning">
                    Are you sure you that {{ object.first_name }} {{ object.last_name }} is not good enough for us?
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/delete_confirm_teacher.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <h4>{{ object.profile.first_name }} {{ object.profile.last_name }}</h4>
                <h5>Age: {{ object.profile.age }} year(s)</h5>
                <button type="submit" value="Delete" class="btn btn-warning">
                    Are you sure you want to delete "{{ object.profile.first_name }} {{ object.profile.last_name }}"?
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/edit_student.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div>
        <form enctype="multipart/form-data" method="POST" class="create-form">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Create" class="btn btn-success">
                    Confirm changes
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/edit_user_profile.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div>
        <form enctype="multipart/form-data" method="POST" class="create-form">

            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Create" class="btn btn-success">
                    Confirm changes
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/groups_list.html
{% extends "index.html" %}

{% block content %}
        {% if user.is_authenticated %}
            {% if user.is_staff %}
                <a href="{% url 'admin:accounts_group_add' %}"
                class="btn btn-sm btn-success border-white ">Create new group</a><br><br>
            {% endif %}
        {% else %}
                <p class="lead">Access denied!</p>
                <p class="lead">Pls, Login to view current page!</p>
            <p class="lead">
                <a href="{% url "login" %}"
                   class="btn btn-lg btn-warning fw-normal border-white bg-white">Login</a>
        {% endif %}

    <br>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            {% if user.is_authenticated %}
            <th scope="col">#</th>
            <th scope="col">Department</th>
            <th scope="col">Classroom</th>

            {% if user.is_staff %}

            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
            {% endif %}
            {% endif %}


        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            {% if user.is_authenticated %}
                {% if user.is_staff %}
            <tr>
                <th scope="row">{{ group.id }}</th>
                <td>{{ group.get_department_display }}</td>

                <td>{{ group.classroom}}</td>
                <th scope="col"><a type="button" class="btn btn-warning"
                href="{% url "admin:accounts_group_change"  group.id  %}"> Edit</a></th>
            <th scope="col"><a type="button" class="btn btn-danger"
                href="{% url 'accounts:delete_group' group.id  %}">Delete</a></th>
                {% else %}
            <tr>
                <th scope="row">{{ group.id }}</th>
                <td>{{ group.get_department_display }}</td>
                <td>{{ group.classroom}}</td>
                {% endif %}
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/accounts/templates/student_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form enctype="multipart/form-data" method="POST" class="create-form">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Create" class="btn btn-success">
                    Create
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/students_list.html
{% extends "index.html" %}

{% block content %}

    {% if user.is_staff %}

        <a href="{% url 'admin:accounts_customuser_add' %}"
           class="btn btn-sm btn-success border-white ">Create new student's profile</a><br><br>
    {% endif %}

    <table class="table table-dark table-striped" >
        <thead>
        <tr>

            {% if user.is_authenticated %}
                <th scope="col">Avatar</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Birthdate</th>
                <th scope="col">Age</th>
                {% if user.is_staff %}
                <th scope="col">CV</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
                {% endif %}
            {% else %}
                <p class="lead">Access denied!</p>
                <p class="lead">Pls, Login to view current page!</p>
                <p class="lead">
                <a href="{% url "login" %}"
                   class="btn btn-lg btn-warning fw-normal border-white bg-white">Login</a>
            {% endif %}
        </tr>
        </thead>

        <tbody style="vertical-align: baseline">
        {% for student in students %}

    {% if user.is_authenticated %}
{#    {% if user.is_staff %}#}
            <tr>

                {% if student.profile.photo %}

                    {% if not student.social_auth.exists %}
                    <th scope="row"><a type="button" href="{% url "profile" student.username %}">
                        <img src="{{ student.profile.photo.url }}"  alt="Image" width="50" height="50" class="rounded-circle" /></a>
                    {% elif student.social_auth.exists %}
                    <th scope="row"><a type="button" href="{% url "profile" student.username %}">
                        <img src="{{ student.profile.photo }}"  alt="Image" width="50" height="50" class="rounded-circle" /></a>
                    </th>
                        {% endif %}
                {% else %}<td>N/A</td>{% endif %}
                <td>{{ student.profile.first_name }}</td>
                <td>{{ student.profile.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.profile.birthdate }}</td>
                    {% if student.profile.birthdate %}
                        <td>{{ student.profile.age }}</td>{% else %}<td>Undefined age</td>{% endif %}
            {% if user.is_staff %}
            <td>
                    {% if student.cv_file %}<a href="{% url "student:download_pdf_file" student.id  %}"
                                               class="btn btn-primary">
                        <i class="fa fa-download"></i>Download CV</a>
                    {% else %}<h6>No CV to download</h6>{% endif %}

            </td>
                <th scope="col"><a type="button" class="btn btn-warning"
                                   href="{% url 'accounts:update_student' student.id %}"> Edit</a>
                </th>
                <th scope="col"><a type="button" class="btn btn-danger"
                                   href="{% url 'accounts:delete_student' student.id %}">Delete</a>
                </th>
              {% endif %}
        {% endif %}


        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/accounts/templates/teachers_list.html
{% extends "index.html" %}
{% include static %}
{#    {% if user.is_authenticated %}#}
{% block content %}
    {% if user.is_staff %}
    <a href="{% url 'admin:accounts_customuser_add' %}"
       class="btn btn-sm btn-success border-white ">Create new teacher's profile</a><br><br>
    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Photo</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birthdate</th>
            <th scope="col">Age</th>
            <th scope="col">Experience</th>
            <th scope="col">Groups</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                 {% if teacher.profile.photo %}

                     {% if not teacher.social_auth.exists %}
                    <th scope="row"><a type="button" href="{% url "profile" teacher.username %}">
                        <img src="{{ teacher.profile.photo.url }}"  alt="Image" width="50" height="50" class="rounded-circle" /></a>
                    </th>
                         {% elif student.social_auth.exists %}
                         <th scope="row"><a type="button" href="{% url "profile" teacher.username %}">
                        <img src="{{ teacher.profile.photo }}"  alt="Image" width="50" height="50" class="rounded-circle" /></a>
                    </th>
                         {% endif %}

                {% else %}<td>N/A</td>{% endif %}
                <td>{{ teacher.profile.first_name }}</td>
                <td>{{ teacher.profile.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.birthday }}</td>
                {% if teacher.profile.birthdate %}
                    <td>{{ teacher.profile.age }}</td>
                {% else %}
                    <td>Undefined age</td>
                {% endif %}
               <td>{{ teacher.experience }}</td>
                <th scope="col"><a type="button" class="btn btn-success"
                href="{% url 'admin:accounts_customuser_change' teacher.id  %}">Show groups</a></th>
                <th scope="col"><a type="button" class="btn btn-warning"
                href="{% url 'admin:accounts_customuser_change' teacher.id  %}"> Edit</a></th>
                <th scope="col"><a type="button" class="btn btn-danger"
                href="{% url 'accounts:delete_teacher' teacher.id  %}">Delete</a></th>
            </tr>

        {% endfor %}
                {% else %}
         <p class="lead">Access denied!</p>
                <p class="lead">Pls, Login to view current page!</p>
                <p class="lead">
                <a href="{% url "login" %}"
                   class="btn btn-lg btn-warning fw-normal border-white bg-white">Login</a>
        {% endif %}
        </tbody>
    </table>

{% endblock %}

src/accounts/templates/update_customuser.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div>
        <form method="POST" class="create-form">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <p>
                <button type="submit" value="Login" class="btn btn-success">
                    Confirm changes
                </button>
            </p>
        </form>
    </div>
{% endblock %}

src/accounts/templates/view_user_profile.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class=" image d-flex flex-column justify-content-center align-items-center">
            <button class="btn-custom ">

                {% if not profile.user.social_auth.exists %}
                <img src="{{ profile.photo.url }}" height="125" width="125" class="rounded-circle" />
                {% elif  profile.user.social_auth.exists %}
                <img src="{{ profile.photo }}" height="125" width="125" class="rounded-circle" />
                {% endif %}

            </button> <span class="name mt-3">{{ profile.full_name | upper }}</span>
            <span class="idd">{{ profile.user.position }}</span>
            <div class="d-flex flex-row justify-content-center align-items-center gap-2">
                <span class="idd1">{{ profile.user.email }}</span>
                <span><i class="fa fa-copy"></i></span>
            </div>
            {% if user.is_student %}
            <div class="d-flex flex-row justify-content-center align-items-center mt-3">
                <span class="number"> {{ profile.grade }} / 100 <span class="follow">Points</span>
                </span>
            </div>
            {% endif %}
            <div class=" d-flex mt-2">
           <span class="idd1">@{{ profile.user.username }}</span>
        </div>
            <div class="text mt-3">
            <span>{{ profile.full_name |title }} is a {{ profile.user.position }} in this beautiful Learning LMS system .<br>
                <br> {{ user.profile.job_title }}  </span>
        </div> <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center">
            <span><i class="fa fa-twitter"></i></span>
            <span><i class="fa fa-facebook-f"></i></span>
            <span><i class="fa fa-instagram"></i></span>
            <span><i class="fa fa-linkedin"></i></span>
        </div> <div class=" px-2 rounded mt-4 date ">
            <span class="join">Joined: {{ user.date_joined }}</span>
        </div>

        </div>
    </div>
</div>

{% endblock %}