src/accounts/urls.py
from django.urls import path
from accounts.views import (
    UpdateStudentView,
    DeleteStudentView,
    StudentListView,
    FileDownloadView,
    GroupListView,
    CreateGroupView,
    UpdateGroupView,
    DeleteGroupView,
    TeachersListView,
    CreateTeacherView,
    UpdateTeacherView,
    DeleteTeacherView,
    ShowGroupsView,
)

app_name = "accounts"

urlpatterns = [
    path("", StudentListView.as_view(), name="get_students"),
    path("update/<str:pk>/", UpdateStudentView.as_view(), name="update_student"),
    path("delete/<str:pk>/", DeleteStudentView.as_view(), name="delete_student"),
    path("download/<uuid:pk>/", FileDownloadView.as_view(), name="download_pdf_file"),
    path("get-groups/", GroupListView.as_view(), name="get_groups"),
    path("create-group/", CreateGroupView.as_view(), name="create_group"),
    path("update-group/<int:pk>/", UpdateGroupView.as_view(), name="update_group"),
    path("delete-group/<int:pk>", DeleteGroupView.as_view(), name="delete_group"),
    path("get-teachers", TeachersListView.as_view(), name="get_teachers"),
    path("create-teacher/", CreateTeacherView.as_view(), name="create_teacher"),
    path("update-teacher/<str:pk>/", UpdateTeacherView.as_view(), name="update_teacher"),
    path("delete-teacher/<str:pk>/", DeleteTeacherView.as_view(), name="delete_teacher"),
    path("show-groups/<str:pk>/", ShowGroupsView.as_view(), name="show_groups"),
]

src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
    UserRegistrationView,
    UserLoginView,
    ActivateUserView,
    CustomUserProfileUpdateView,
    UserLogOutView,
    CustomUserProfileView,
    PrivacyPolicyView,
    CustomUserUpdateView,
    IndexView,
)
from accounts.views import NotFoundView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", IndexView.as_view(), name="index"),
    path("registration/", UserRegistrationView.as_view(), name="user_registration"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate"),
    path("oauth/", include("social_django.urls", namespace="social")),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogOutView.as_view(), name="logout"),
    path("profile/<str:username>/", CustomUserProfileView.as_view(), name="profile"),
    path("user_settings/<uuid:pk>/", CustomUserUpdateView.as_view(), name="edit_customuser"),
    path("edit_profile/<uuid:pk>/", CustomUserProfileUpdateView.as_view(), name="edit_profile"),
    path("privacy_policy/", PrivacyPolicyView.as_view(), name="privacy"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = NotFoundView.as_view()

src/templates/index.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>LMS Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

    </style>


          <!-- Custom styles for this template -->
    <link href="{% static "/css/cover.css" %}" rel="stylesheet">

  </head>

  <body class="d-flex h-100 text-center text-white bg-dark" style="background-image: url('https://images8.alphacoders.com/105/thumb-1920-1054256.jpg');
  height: 100vh;">
  <div id="fb-root"></div>

<div class="cover-container d-flex w-100 h-100 mx-auto pb-5 flex-column ">
    <header class="mb-auto">
        <div>
            <br><h3 class="float-md-start">LMS SYSTEM</h3>

            <nav class="nav nav-masthead justify-content-center float-md-end " >
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle"
                                 id="dropdownUser1"
                                 data-bs-toggle="dropdown"
                                 aria-expanded="false">
                        {% if user.is_authenticated and not user.social_auth.exists %}
                    <img src="{{ user.profile.photo.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                        {% elif  user.is_authenticated and user.social_auth.exists %}
                    <img src="{{ user.profile.photo }}" alt="mdo" width="32" height="32" class="rounded-circle">
                            {% else %}
                    <img src="{% static "img/default.png" %}" alt="mdo" width="32" height="32" class="rounded-circle">
                        {% endif %}

                    </a>
                    <ul class="dropdown-menu text-sm-start-start" aria-labelledby="dropdownUser1" style="">
            {% if user.is_authenticated %}
                <li><a class="dropdown-item disabled" >Hello, {{ user.username }}</a></li>
                <li><hr class="dropdown-divider"></li>
            {% if user.is_staff %}
                <li><a class="dropdown-item" href="{% url "admin:index" %}">Admin panel</a></li>
            {% endif %}
                <li><a class="dropdown-item" href="{% url "edit_customuser" user.id %}">User settings</a></li>
                <li><a class="dropdown-item" href="{% url "profile" user.username %}">View profile</a></li>
                <li><a class="dropdown-item" href="{% url "edit_profile" user.id %}">Edit profile</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url "logout" %}">Sign out</a></li>
            {% else %}
                <li><a class="dropdown-item disabled" >Hello, Guest!</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url "login" %}">Login</a></li>
                <li><a class="dropdown-item" href="{% url "user_registration" %}">Sign Up</a></li>

            {% endif %}

          </ul>
        </div>

                <a class="nav-link active" aria-current="page" href="{% url "index" %}">Home</a>
                <a class="nav-link" href="{% url "accounts:get_students" %}">Students</a>
                <a class="nav-link" href="{% url "accounts:get_teachers" %}">Teachers</a>
                <a class="nav-link" href="{% url "accounts:get_groups" %}">Groups</a>
                <form method="GET" class="nav-link"
                      action="{% url "accounts:get_students" %}">
                    <input type="search"
                           class="form-control ds-input"
                           id="search_text"
                           name="search_text"
                           placeholder="Search..."
                           aria-label="Search docs for..."
                           autocomplete="on"
                           data-bd-docs-version="5.1"
                           spellcheck="false"
                           aria-autocomplete="list"
                           aria-expanded="false"
                           aria-owns="algolia-autocomplete-listbox-0"
                           dir="auto"
                           style="position: relative; vertical-align: top;">
                </form>

            </nav>
        </div>
    </header>

    <main class="px-3">

            {% block content %}
            <h1>Good place for the project</h1>
            <p class="lead">This page is a place where the LMS SYSTEM is shown.</p>
            <p class="lead">
                <a href="#"
                   class="btn-primary btn-lg btn-warning fw-normal border-white bg-white" style="opacity: 85%; color: #101214">Learn
                    more</a>
            </p>
            {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/"
                                 class="text-light">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>
</html>

src/templates/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}